
// This file was generated by robots for you at 2019-03-01 00:23:26.23089103 +0300 MSK m=+0.006787197
package load_images

type TypeIn struct {
	RawImages   []string `json:"rawImages"`
	Phone       string   `json:"phone"`
	Year        *int     `json:"year"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Price       int      `json:"price"`
}

type TypeOut struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Price       int      `json:"price"`
	Photos      []string `json:"photos"`
	Phone       string   `json:"phone"`
	Year        *int     `json:"year"`
}

func Handle(input TypeIn) TypeOut {
	return TypeOut{
		Name        : input.Name,
		Description : input.Description,
		Price       : input.Price,
		Photos      : input.RawImages,
		Phone       : input.Phone,
		Year        : input.Year,
	}
}
