// This file was generated by robots for you at 2019-03-01 02:16:53.654759967 +0300 MSK m=+0.007037983
package load_images

type TypeIn struct {
	Description string   `json:"description"`
	Name        string   `json:"name"`
	Phone       string   `json:"phone"`
	Price       int      `json:"price"`
	RawImages   []string `json:"rawImages"`
	Year        *int     `json:"year"`
}

type TypeOut struct {
	Description string   `json:"description"`
	Name        string   `json:"name"`
	Phone       string   `json:"phone"`
	Photos      []string `json:"photos"`
	Price       int      `json:"price"`
	Year        *int     `json:"year"`
}

func Handle(input TypeIn) TypeOut {
	return TypeOut{
		Name:        input.Name,
		Description: input.Description,
		Price:       input.Price,
		Photos:      input.RawImages,
		Phone:       input.Phone,
		Year:        input.Year,
	}
}
