
// This file was generated by robots for you at 2019-03-01 02:17:26.11503161 +0300 MSK m=+0.007699643
package create

type TypeIn struct {
	Description string   `json:"description"`
	Name        string   `json:"name"`
	Phone       string   `json:"phone"`
	Photos      []string `json:"photos"`
	Price       int      `json:"price"`
	Year        *int     `json:"year"`
}

type TypeOut int

func Handle(input TypeIn) TypeOut {
	return 0
}
