
// This file was generated by robots for you at 2019-03-01 00:20:54.518034811 +0300 MSK m=+0.012275742
package create

type TypeIn struct {
	Price       int      `json:"price"`
	Photos      []string `json:"photos"`
	Phone       string   `json:"phone"`
	Year        *int     `json:"year"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
}

type TypeOut int

func handle(input TypeIn) TypeOut {
	return 0
}
