// This file was generated by robots for you at 2019-03-01 02:17:21.902835418 +0300 MSK m=+0.007041600
package transform

import "encoding/json"

type TypeIn string

type TypeOut struct {
	Description string   `json:"description"`
	Name        string   `json:"name"`
	Phone       string   `json:"phone"`
	Price       int      `json:"price"`
	RawImages   []string `json:"rawImages"`
	Year        *int     `json:"year"`
}

func Handle(input TypeIn) TypeOut {
	output := TypeOut{}
	json.Unmarshal([]byte(input), &output)
	return output
}
