
// This file was generated by robots for you at 2019-03-01 00:19:07.841516126 +0300 MSK m=+0.010313676
package transform

import "encoding/json"

type TypeIn string

type TypeOut struct {
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Price       int      `json:"price"`
	RawImages   []string `json:"rawImages"`
	Phone       string   `json:"phone"`
	Year        *int     `json:"year"`
}

func handle(input TypeIn) TypeOut {
	output := TypeOut{}
	json.Unmarshal([]byte(input), &output)
	return output
}
